### ISSUE TITLE
Failed to FindPattern CTriggerMoved_ZTS or CTouchLinks_ZTI

### ISSUE THREAD

**Issue by roby2014** [Vauff/sm-ext-PhysHooks#3]
Hi, are the signatures correct? Some plugins that take usage of this extension are failing because it can't find `CTriggerMoved_ZTS` and `CTouchLinks_ZTI`:

`[09] <FAILED> file "PhysHooks.ext.2.csgo.so": Failed to FindPattern CTriggerMoved_ZTS or CTouchLinks_ZTI`

Game: `CS:GO`
OS: `Linux`
SourceMod Version Information:
```
SourceMod Version: 1.11.0.6936
SourcePawn Engine: 1.11.0.6936, jit-x86 (build 1.11.0.6936)
SourcePawn API: v1 = 5, v2 = 16
Compiled on: Jul 25 2023 19:13:20
Built from: https://github.com/alliedmodders/sourcemod/commit/8b91e2ff
Build ID: 6936:8b91e2ff
http://www.sourcemod.net/
```

**Comment by Vauff** [comment]
I'm not seeing this behaviour on the latest Linux release, are you sure you're [up to date](https://github.com/Vauff/sm-ext-PhysHooks/releases)?

**Comment by roby2014** [comment]
Oops, my bad. Some stupid problems, it works fine now, sorry for the issue.
